### PR TITLE
InvertPin(...) was using wrong "shadow register"

### PR DESCRIPTION
**Pull request by qstbck**
Affects IOPi.cs library (I2C I/O expander)

### CODE REVIEW

**Comment by abelectronicsuk** [comment]
Thank you for finding the bug.  I have merged your fix into the main branch.

**Comment by carldebilly** [comment]
@abelectronicsuk Don't forget to push a new version on Nuget :-).

**Comment by abelectronicsuk** [comment]
Thanks for the reminder.  I have uploaded a nuget package with the bug fix, it is currently awaiting validation so it should be available soon.

**Comment by carldebilly** [comment]
If you want I can help you automating the build and publish to nuget through appveyor (free for open source projets).

**Comment by abelectronicsuk** [comment]
Thank you for the offer, but for how often the library gets updated it is just as easy for me to do it manually using github and nuget.

**Pull request merged**
